# Simple package

name: simple-package
parent: default

matches:
  - trigger: ":#hw"
    replace: "[#espanso-utility](https://github.com/pietrzak-pro/espanso-utility) loves [#programmers](https://en.wikipedia.org/wiki/Programmer)"
